# Generated by Django 3.2.5 on 2021-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dare_description', models.TextField()),
                ('rules', models.TextField()),
                ('goal', models.IntegerField()),
                ('image', models.URLField()),
                ('is_open', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('date_for_dare', models.DateTimeField()),
                ('for_charity', models.TextField()),
                ('charity_url', models.URLField()),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
    ]
