# Generated by Django 3.2.5 on 2021-11-07 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dare_description', models.TextField(default='')),
                ('rules', models.TextField(default='')),
                ('goal', models.IntegerField()),
                ('image', models.URLField()),
                ('is_open', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('date_for_dare', models.DateTimeField()),
                ('for_charity', models.TextField()),
                ('charity_url', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_dares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dollars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.TextField()),
                ('anonymous', models.BooleanField()),
                ('dares', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dollars', to='dares.dares')),
                ('supporter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='supporter_dollars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
