# Generated by Django 3.2.5 on 2021-09-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dares', '0002_dollars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dollars',
            old_name='dare_id',
            new_name='dare',
        ),
    ]
