# Generated by Django 3.2.5 on 2021-09-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dares', '0003_rename_dare_id_dollars_dare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dollars',
            old_name='dare',
            new_name='dares',
        ),
    ]
