# Generated by Django 3.2.5 on 2021-11-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dares', '0005_auto_20210914_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('dares', models.ManyToManyField(to='dares.Dares')),
            ],
        ),
    ]
