# Generated by Django 3.2.5 on 2021-11-05 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dares', '0006_charity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dollars',
            name='supporter',
        ),
    ]
